# Generated by Django 4.2.3 on 2023-07-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=50, unique=True)),
                ('encoded_secret_key', models.BinaryField(max_length=255)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
